# -*- coding: utf-8 -*-
"""市立鼓山高級中學_131009_劉家銘

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a3b1YOk4MV1WTDqp1W20KDFAfJbcIh-_
"""

import pandas as pd
import json
import matplotlib.pyplot as plt

# 讀取 CSV 檔案
df = pd.read_csv("觀光遊憩據點按縣市及遊憩據點交叉分析.csv")

# 1. 計算每個縣市每個月的觀光人數，並繪製箱型圖
def plot_boxplot_by_city(df, city):
    city_data = df[df['縣市'] == city]
    plt.figure(figsize=(10, 6))
    plt.boxplot(city_data.iloc[:, 2:].values)  # 假設從第三列開始是各月份的觀光人數
    plt.title(f"{city} 各月份觀光人數箱型圖")
    plt.xlabel("月份")
    plt.ylabel("觀光人數")
    plt.xticks(rotation=45)
    plt.show()

# 繪製箱型圖，比較不同產品類別的銷售額
def plot_boxplot_by_category(df):
    plt.figure(figsize=(10, 6))
   df.boxplot(column='monthly_sales', by='product_category')
    plt.title('不同產品類別的每月銷售額分佈')
    plt.xlabel('產品類別')
    plt.ylabel('每月銷售額')
    plt.xticks(rotation=45)
    plt.show()

# 2. 根據使用者輸入的條件查詢飯店
def search_hotel(city, service_info, lowest_price, ceiling_price):
    with open("HotelList.json", "r") as f:
        hotels = json.load(f)

    results = [
        hotel for hotel in hotels
        if hotel['City'] == city and service_info in hotel['ServiceInfo'] and
           lowest_price <= hotel['LowestPrice'] <= ceiling_price
    ]

    if results:
        for result in results[:5]:
            print(result)
    else:
        print("找不到符合條件的飯店")

# 調用函數示例
plot_boxplot_by_city(df, '台北市')
plot_boxplot_by_category(df)
search_hotel('台北市', '游泳池', 1000, 3000)