# -*- coding: utf-8 -*-
"""國立彰化女子高級中學_10829_蔡美恩.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GDykbMvTst1pTtNks3UVzAylQm2aIqLk
"""

!wget -O TaipeiSansTCBeta-Regular.ttf https://drive.google.com/uc?id=1eGAsTN1HBpJAkeVM57_C7ccp7hbgSz3_&export=download
import matplotlib.pyplot as plt
import matplotlib
import matplotlib.font_manager
matplotlib.font_manager.fontManager.addfont('TaipeiSansTCBeta-Regular.ttf')
matplotlib.rc('font', family='Taipei Sans TC Beta')

import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)


df=pd.read_csv('觀光遊憩據點按縣市及遊憩據點交叉分析.csv')

county_name_mapping = {
    '金門縣': 'Kinmen',
    '臺東縣': 'Taitung',
    '澎湖縣': 'Penghu',
    "連江縣": "Lianjiang"
}
df['縣市'] = df['縣市'].map(county_name_mapping)

import json

with open('HotelList.json', 'r', encoding='utf-8-sig') as file:
  data = json.load(file)

df['小計'] = pd.to_numeric(df['小計'], errors='coerce')
月份欄位 = df.columns[4:-1]
df['總和'] = df[月份欄位].sum(axis=1)
縣市總和 = df.groupby('縣市')['小計'].agg(['median', 'max']).reset_index()
a=df.groupby('縣市')['小計'].sum().reset_index()

plt.figure(figsize=(12, 6))
df.boxplot(column='小計', by='縣市')
plt.xlabel('County', fontsize=14)
plt.ylabel('Tourists', fontsize=14)
plt.grid(axis='y')
plt.xticks(rotation=45)  # 旋轉 x 軸標籤
plt.tight_layout()

for i, 縣市 in enumerate(county_name_mapping.values()):
    最大值 = 縣市總和.loc[縣市總和['縣市'] == 縣市, 'max'].values[0]
    中位數 = 縣市總和.loc[縣市總和['縣市'] == 縣市, 'median'].values[0]

    plt.text(i + 1, 最大值, f'Max: {int(最大值)}', ha='center', va='bottom', fontsize=10,color='blue' )
    plt.text(i + 1, 中位數, f'Median: {int(中位數)}', ha='center', va='top', fontsize=10,color='black' )


plt.savefig('001.jpg')
plt.clf()
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)








hotels_df = pd.json_normalize(data['Hotels'])
user_input_city = input("請輸入縣市名稱:(例:彰化縣) ")
matching_hotels = hotels_df[hotels_df['PostalAddress.City'] == user_input_city]
if matching_hotels.empty:
        print("未找到符合地點和特殊需求的旅館/民宿")
else:
    # 詢問是否有特殊需求，直接按enter或輸入'無'可以跳過，即代表無需求
    user_input_special_condition = input('請輸入特殊需求:')

    if user_input_special_condition.lower() and user_input_special_condition.lower()!='無'and user_input_special_condition != '':
        matching_hotels = matching_hotels[matching_hotels['ServiceInfo'].str.contains(user_input_special_condition, case=False, na=False)]
        from tabulate import tabulate
        if user_input_special_condition.empty:
            print("未找到符合地點和特殊需求的旅館/民宿")

    if not matching_hotels.empty:
        user_input_budget = int(input('請輸入預算:'))

        columns_to_display = ['HotelName', 'LowestPrice', 'CeilingPrice', 'Description', 'PostalAddress.Town', 'PostalAddress.StreetAddress']
        print(matching_hotels[columns_to_display].head(5).to_string(index=False))
    else:
        print("未找到符合預算的旅館/民宿")
        if user_input_budge.empty:
            print("未找到符合預算的旅館/民宿")
        else:
            print("在", user_input_city, "的符合所有條件的旅館有：")
            print(matching_hotels_by_budget[['HotelName', 'LowestPrice', 'CeilingPrice', 'Description', 'PostalAddress.Town', 'PostalAddress.StreetAddress']].head(5).to_string(index=False))