# -*- coding: utf-8 -*-
"""HW-3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ydTjzN9hUnbw_Sv9vlY8VlDYy0vB4dNw
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

# 讀取CSV檔
df = pd.read_csv('觀光遊憩據點按縣市及遊憩據點交叉分析.csv')
months = df.columns[4:-1]  # 獲取所有月份的列
df[months] = df[months].apply(pd.to_numeric, errors='coerce')  # 轉換為數值
county_mapping = {
   '金門縣': 'Kinmen',
   '臺東縣': 'Taitung',
   '澎湖縣': 'Penghu',
   '連江縣': 'Lianjiang'
}
df['縣市']=df['縣市'].replace(county_mapping)
# 按縣市匯總遊客數
county_summary = df.groupby('縣市')[months].sum().reset_index()


# 轉換資料結構以符合boxplot需求
df_melted = pd.melt(county_summary, id_vars=['縣市'], value_vars=months, var_name='月份', value_name='遊客數')

# 繪製箱型圖
plt.figure(figsize=(12, 6))
sns.boxplot(x='縣市', y='遊客數', data=df_melted)

stats = df_melted.groupby('縣市')['遊客數'].agg(['median', 'max'])
# 在圖上添加中位數和最大值的標註
for i, county in enumerate(stats.index):
    plt.text(i, stats['median'][county], f'Median: {int(stats["median"][county])}',
             ha='center', va='bottom', fontsize=10, color='black')
    plt.text(i, stats['max'][county], f'Max: {int(stats["max"][county])}',
             ha='center', va='bottom', fontsize=10, color='blue')
# 調整圖表格式
plt.xlabel('County', fontsize=14)
plt.ylabel('Tourists', fontsize=14)
plt.grid(axis='y')
plt.xticks(rotation=45)
plt.tight_layout()


plt.savefig('001.jpg')

import json

import json

with open('HotelList.json', 'r', encoding='utf-8-sig') as file:
    data = json.load(file)

# 將 JSON 轉換為 DataFrame
hotels_df = pd.json_normalize(data['Hotels'])

# 用戶輸入的城市名稱
user_input_city = input()

matching_hotels = hotels_df[hotels_df['PostalAddress.City'] == user_input_city]

if matching_hotels.empty:
    print("未找到符合地點的旅館/民宿")
else:
  user_input_special_condition = input()

  if user_input_special_condition.lower() and user_input_special_condition.lower()!='無':
    matching_hotels = matching_hotels[matching_hotels['ServiceInfo'].str.contains(user_input_special_condition, case=False, na=False)]
    from tabulate import tabulate
    sec_matching_hotels = matching_hotels[matching_hotels['ServiceInfo'] == user_input_special_condition]

    if sec_matching_hotels.empty:
     print("未找到符合地點的旅館/民宿")
    else:
     price=input()
     final_matching_hotels = sec_matching_hotels[sec_matching_hotels['LowestPrice'] <= int(price)]
     if not final_matching_hotels.empty:
            # 使用 Pandas 內建方法輸出前五個結果
            columns_to_display = ['HotelName', 'LowestPrice', 'CeilingPrice', 'Description', 'PostalAddress.Town', 'PostalAddress.StreetAddress']
            print(final_matching_hotels[columns_to_display].head(5).to_string(index=False))
     else:
            print("未找到符合預算的旅館/民宿")

  else:

     price=input()
     final_matching_hotels = matching_hotels[matching_hotels['LowestPrice'] <= int(price)]
     if not final_matching_hotels.empty:
            # 使用 Pandas 內建方法輸出前五個結果
            columns_to_display = ['HotelName', 'LowestPrice', 'CeilingPrice', 'Description', 'PostalAddress.Town', 'PostalAddress.StreetAddress']
            print(final_matching_hotels[columns_to_display].head(5).to_string(index=False))
     else:
            print("未找到符合預算的旅館/民宿")