# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P0JlYZc8FBJr-lzJeVOr1KBayv-uBrXS
"""

import os
for file in os.listdir('/content/drive/MyDrive/'):
    print(file)

import pandas as pd
import matplotlib.pyplot as plt
import json
from google.colab import drive

# 掛載 Google Drive
drive.mount('/content/drive')

# 讀取 CSV 和 JSON 檔案
csv_file = '/content/觀光遊憩據點按縣市及遊憩據點交叉分析.csv'
json_file = '/content/HotelList.json'

df = pd.read_csv(csv_file, encoding='utf-8')  # 調整編碼，確保能正確讀取中文
with open('HotelList.json', 'r', encoding='utf-8-sig') as f:
    HotelList = json.load(f)



# 搜尋符合條件的旅館
def search_hotel(county, special_needs, price_range):
    # ... (搜尋符合條件的旅館的邏輯)
    # ... (這裡省略具體搜尋的程式碼，可以參考 Python 的字典操作)
    print('HotelName\tLowestPrice\tCeilingPrice\tDescription\tPostalAddress_Town\tPostalAddress_StreetAddress')
    # ... (輸出符合條件的旅館資訊)

# 使用者輸入
county = input('請輸入縣市：')
special_needs = input('請輸入特殊需求：')
price_range = int(input('請輸入價位範圍：'))

# 執行函數
plot_boxplot(df)
search_hotel(county, special_needs, price_range)