# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17PrUgofwOVj3xO-yZeV4Na43tTJHeg-L
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 讀取數據
df = pd.read_csv('觀光遊憩據點按縣市及遊憩據點交叉分析.csv')

# 將月份列轉換為數值並匯總
months = df.columns[3:-1]  # 獲取所有月份的列
df[months] = df[months].apply(pd.to_numeric, errors='coerce')  # 轉換為數值

# 將縣市的中文名稱替換為英文名稱
county_name_mapping = {
    '金門縣': 'Kinmen',
    '臺東縣': 'Taitung',
    '澎湖縣': 'Penghu',
    "連江縣": "Lianjiang"
}
df['縣市'] = df['縣市'].replace(county_name_mapping)

# 按縣市匯總遊客數
county_summary = df.groupby('縣市')[months].sum().reset_index()

# 將數據轉換為長格式，方便繪製箱型圖
long_format = county_summary.melt(id_vars='縣市', value_vars=months, var_name='月份', value_name='遊客數')

# 創建圖形
plt.figure(figsize=(12, 6))

# 使用 Seaborn 繪製箱型圖，不使用 palette
boxplot = sns.boxplot(x='縣市', y='遊客數', data=long_format)

# 計算中位數、最大值
stats = long_format.groupby('縣市')['遊客數'].agg(['median', 'max'])

for i, county in enumerate(stats.index):
    plt.text(i, stats['median'][county], f'Median: {int(stats["median"][county])}',
             ha='center', va='bottom', fontsize=10, color='black')
    plt.text(i, stats['max'][county], f'Max: {int(stats["max"][county])}',
             ha='center', va='bottom', fontsize=10, color='blue')

plt.xlabel('County', fontsize=14)
plt.ylabel('Tourists', fontsize=14)
plt.grid(axis='y')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()