# -*- coding: utf-8 -*-
"""「第四週_聊天機器人_Part2.ipynb」的副本

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QViTY27iPiHBnkyZ_zwEZDB2241K_RUo

https://ai.google.dev/

https://ai.google.dev/gemini-api/docs/quickstart?lang=python
"""

from google.colab import userdata
apikey = userdata.get('GOOGLE_API_KEY')

import google.generativeai as genai
genai.configure(api_key = apikey)
model = genai.GenerativeModel("gemini-1.5-flash")
response = model.generate_content("Write a story about a magic backpack.")
print(response.text)

def translate_text(text, target_language):
    prompt = f"Translate the following text to {target_language}: {text}"
    response = model.generate_content(prompt)
    return response.text

def chat_bot():
    print("Welcome to the translation chatbot!")
    print("Type 'exit' to quit.")

    target_language = input("Please specify the target language (e.g., French, Spanish, Chinese): ")

    while True:
        user_input = input("Enter the text you want to translate: ")

        if user_input.lower() == "exit":
            print("Goodbye!")
            break

        translation = translate_text(user_input, target_language)
        print(f"Translation to {target_language}: {translation}")

chat_bot()