# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tU0P0lvjDBjwWcbkE0Ssb6dHJNWWJpQN
"""

import pandas as pd
import matplotlib.pyplot as plt


file_path = 'myExpenses1.csv'
df = pd.read_csv(file_path)


top_10_items = df.groupby('Item')['Amount'].sum().nlargest(10)

plt.figure(figsize=(10,6))
top_10_items.plot(kind='bar')
plt.xlabel("Item")
plt.ylabel("Total Amount Spent")


plt.savefig('001.jpg')


highest_spending_item = top_10_items.idxmax()
highest_spending_amount = top_10_items.max()

print(f"Item with the highest spending is {highest_spending_item}")
print(f"Total amount spent is {highest_spending_amount}\n")


spending_by_day = df.groupby('day')['Amount'].sum()
ordered_days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
spending_by_day = spending_by_day.reindex(ordered_days)

plt.figure(figsize=(8,8))
plt.pie(spending_by_day, labels=spending_by_day.index, autopct='%.0f%%')


plt.savefig('002.jpg')


df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)


highest_spending_days = df.groupby(['day', 'Date'])['Amount'].sum().reset_index()
highest_spending_days = highest_spending_days.loc[highest_spending_days.groupby('day')['Amount'].idxmax()]


for day in ordered_days:
    date = highest_spending_days[highest_spending_days['day'] == day]['Date'].dt.strftime('%Y-%m-%d').values[0]
    print(f"Highest spending day on {day} is {date}")



