# -*- coding: utf-8 -*-
"""「Untitled0.ipynb」的副本

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ULugePD6IU8iOEGjMXXOSkNOIehBUzFp
"""

import pandas as pd
import json
import matplotlib.pyplot as plt

# 讀取 CSV 檔案
def read_csv_and_plot(csv_file):
    # 讀取 CSV
    df = pd.read_csv(csv_file);

    # 假設有'County', 'Year', 'TouristCount'這幾個欄位
    grouped_data = df.groupby(['County', 'Year'])['TouristCount'].sum().unstack()

    # 繪製箱型圖
    plt.figure(figsize=(10, 6))
    boxplot = grouped_data.plot.box(showmeans=True)

    plt.title('Tourist Count by County and Year')
    plt.ylabel('Number of Tourists')
    plt.xticks(rotation=45)

    # 計算並標註最大值與中位數
    for county in grouped_data.columns:
        plt.text(county, grouped_data[county].max(), 'Max: {}'.format(grouped_data[county].max()),
                 horizontalalignment='center', color='red')
        plt.text(county, grouped_data[county].median(), 'Median: {}'.format(grouped_data[county].median()),
                 horizontalalignment='center', color='blue')

    plt.show()

# 讀取 JSON 檔案
def search_hotels(json_file, city, service_info, lowest_price, ceiling_price):
    with open(json_file, 'r', encoding='utf-8') as f:
        hotels = json.load(f)

    # 篩選符合條件的旅館
    filtered_hotels = []
    for hotel in hotels:
        if (hotel['City'] == city and
            (service_info == '無' or service_info in hotel.get('ServiceInfo', [])) and
            lowest_price <= hotel['LowestPrice'] <= ceiling_price):
            filtered_hotels.append(hotel)

    # 輸出前5筆旅館資訊
    if filtered_hotels:
        print("符合條件的旅館:")
        for hotel in filtered_hotels[:5]:
            print(pd.Series({
                'HotelName': hotel['HotelName'],
                'LowestPrice': hotel['LowestPrice'],
                'CeilingPrice': hotel['CeilingPrice'],
                'Description': hotel['Description'],
                'PostalAddress.Town': hotel['PostalAddress']['Town'],
                'PostalAddress': hotel['PostalAddress']['Address'],
                'StreetAddress': hotel['StreetAddress']
            }).to_string())
    else:
        print("找不到符合條件的旅館。")

# 主程式
if __name__ == '__main__':
    # 執行 CSV 部分
    read_csv_and_plot('觀光遊憩據點按縣市及遊憩據點交叉分析.csv')

    # 用戶輸入
    city = input("請輸入縣市: ")
    service_info = input("請輸入特殊需求（無可直接按 enter 跳過）: ")
    lowest_price = int(input("請輸入最低價位（1~20000）: "))
    ceiling_price = int(input("請輸入最高價位（1~20000）: "))

    # 執行 JSON 部分
    search_hotels('HotelList